### ISSUE TITLE
Exception: Executable 'ffprobe' not found

### ISSUE THREAD

**Issue by ZZLinvec** [sdbds/SVD-webui#3]
大佬可以帮忙看看这个问题怎么搞吗？

win11+2080ti22G

运行点击生成后会出现下面的这个日志，我是直接用示例图的

```
(venv) PS D:\project\AI_video\SVD-webui> .\run_gui.ps1
D:\project\AI_video\SVD-webui\venv\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
Initialized embedder #1: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #3: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
Initialized embedder #4: ConcatTimestepEmbedderND with 0 params. Trainable: False
Restored from checkpoints/svd.safetensors with 0 missing and 0 unexpected keys
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
##############################  Sampling setting  ##############################
Sampler: EulerEDMSampler
Discretization: EDMDiscretization
Guider: LinearPredictionGuider
Sampling with EulerEDMSampler for 26 steps:   0%|                                               | 0/26 [00:00<?, ?it/s]D:\project\AI_video\SVD-webui\venv\lib\site-packages\torch\utils\checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
Sampling with EulerEDMSampler for 26 steps:  96%|████████████████████████████████████▌ | 25/26 [01:28<00:03,  3.56s/it]
Traceback (most recent call last):
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\ffmpy.py", line 95, in run
    self.process = subprocess.Popen(
  File "C:\Program Files\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\queueing.py", line 427, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\blocks.py", line 1493, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\blocks.py", line 1382, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\components\video.py", line 220, in postprocess
    processed_files = (self._format_video(y), None)
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\components\video.py", line 270, in _format_video
    and not processing_utils.video_is_playable(video)
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\processing_utils.py", line 701, in video_is_playable
    output = probe.run(stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\ffmpy.py", line 105, in run
    raise FFExecutableNotFoundError(
ffmpy.FFExecutableNotFoundError: Executable 'ffprobe' not found
Traceback (most recent call last):
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\ffmpy.py", line 95, in run
    self.process = subprocess.Popen(
  File "C:\Program Files\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\queueing.py", line 427, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\blocks.py", line 1493, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\blocks.py", line 1382, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\components\video.py", line 220, in postprocess
    processed_files = (self._format_video(y), None)
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\components\video.py", line 270, in _format_video
    and not processing_utils.video_is_playable(video)
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\processing_utils.py", line 701, in video_is_playable
    output = probe.run(stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\ffmpy.py", line 105, in run
    raise FFExecutableNotFoundError(
ffmpy.FFExecutableNotFoundError: Executable 'ffprobe' not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\queueing.py", line 472, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "D:\project\AI_video\SVD-webui\venv\lib\site-packages\gradio\queueing.py", line 436, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: Executable 'ffprobe' not found
```

**Comment by sdbds** [comment]
看起来是没装ffmpeg，不过应该和opencv一块装好了的。

**Comment by xx025** [comment]
opencv-python 可能存在一些编码问题，我用了这种方法

https://github.com/xx025/stable-video-diffusion-webui/blob/c5411099258b527e63ab88eb0527dcfd7992254e/modules/model.py#L233C1-L245C62

https://github.com/xx025/stable-video-diffusion-webui/blob/c5411099258b527e63ab88eb0527dcfd7992254e/modules/img_tool.py#L115
